### ISSUE TITLE
Bot gives multiple responses 

### ISSUE THREAD

**Issue by BenPeterson** [HUD-Digital-Services/customer-service-bot#4]
Can we get rid of the second dialog from the bot after it answers? The first one "I hope that helps..." I think does the job of being clear and prompting for the next input by the user.

![screen shot 2017-09-20 at 5 13 03 pm](https://user-images.githubusercontent.com/7881766/30667953-322a00f4-9e27-11e7-9921-1eb492d74d25.png)

**Comment by markbubel** [comment]
We can get rid of a dialog because I agree it's too much, _but_ there's a deeper explanation as to why there's two dialogs after the bot returns the answer.

1. User enters the dialog, bot says: "Ask about low income...."
2. User asks question.
3. Bot returns the answer.
4. Bot says "I hope this helps...."
5. Bot needs to be ready for another question, so bot starts the dialog over from the beginning.

Since the dialog is repeated after every question, you'll always see the bot's first comment: "Ask about low income...".

That's the way the MS Bot Framework handles repeating dialogs. You can see this with the `session.replaceDialog('dialogName') `method.

All that said, we can remove the "I hope that helps...." dialog. Thoughts?

**Comment by markbubel** [comment]
For now I've removed the "I hope this helps..." dialog for each of choices.
